version: '3.9'

services:

  api:
    image: epinux/ncprocess:latest
    build:
      context: ./docker/ncprocess
    ports:
      - 8004:8000
    # command: uvicorn main:app --host 0.0.0.0 --reload
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./ncprocess:/usr/src/app
      - ./docker/ncprocess/api_entrypoint.sh:/usr/src/app/entrypoint.sh
      - download-data:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_PASSWORD='FGX0Im8cROKpFpHPOP8FETmOpLPsiLwEnHHXprOgn2AR7r7cGp'
      - DOWNLOAD_DIR=/usr/src/app/data
    depends_on:
      - redis
    hostname: api

  worker:
    image: epinux/ncprocess:latest
    build:
      context: ./docker/ncprocess
    # command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./ncprocess:/usr/src/app
      - ./docker/ncprocess/celery_entrypoint.sh:/usr/src/app/entrypoint.sh
      - download-data:/usr/src/app/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOWNLOAD_DIR=/usr/src/app/data
    depends_on:
      - api
      - redis

  redis:
    # image: epinux/redis:local
    image: redis/redis-stack:latest
    volumes:
      - redis-data:/data
    volumes:
      - ./ncprocess/redis_data/data:/data
      - ./ncprocess/redis_data/redis-stack.conf:/opt/redis-stack/etc/redis-stack.conf

  dashboard:
    image: epinux/ncprocess:latest
    build: ./docker/ncprocess
    entrypoint: /usr/src/app/entrypoint.sh
    # command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5557:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./docker/ncprocess/flower_entrypoint.sh:/usr/src/app/entrypoint.sh
    depends_on:
      - api
      - redis
      - worker

volumes:
  redis-data:
  download-data:
